#!/bin/sh
bl_dev=/sys/class/backlight/acpi_video0
#bl_dev=/sys/class/backlight/intel_backlight

step=2

case $1 in
  -) echo $(($(cat $bl_dev/brightness) - $step)) > $bl_dev/brightness;;
  +) echo $(($(cat $bl_dev/brightness) + $step)) > $bl_dev/brightness;;
esac
